server:
  port: 8080
spring:
  cache:
    type: none
  datasource:
    url: jdbc:postgresql://localhost:5433/oto_db?currentSchema=xinerji
    username: oto_user
    password: 07104420Gyte
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher